export const businesses = [
  {
    businessId: 1,
    businessName: "West Pecan Coffee + Beer",
    businessPhone: "(512)551-3471",
    streetAddress: "100 W Pecan St.",
    city: "Pflugerville",
    state: "TX",
    zipcode: 78660,
    website: "https://westpecancoffee.com",
    maxOccupancy: 100,
    allowedOccupancyRestriction: 100,
    profileImage: "",
    active: false,
  },
  {
    businessId: 2,
    businessName: "Pokeworks",
    businessPhone: "(512)551-9512",
    streetAddress: "1920 E Riverside Dr.",
    city: "Austin",
    state: "TX",
    zipcode: 78741,
    website: "https://www.pokeworks.com",
    maxOccupancy: 150,
    allowedOccupancyRestriction: 75,
    profileImage: "",
    active: false,
  },
  {
    businessId: 3,
    businessName: "Bella Salon",
    businessPhone: "(512)474-5999",
    streetAddress: "1221 W 6th St.",
    city: "Austin",
    state: "TX",
    zipcode: 78703,
    website: "http://www.bellasalonaustin.com",
    maxOccupancy: 190,
    allowedOccupancyRestriction: 50,
    profileImage: "",
    active: false,
  },
  {
    businessId: 4,
    businessName: "Urban Axes Austin",
    businessPhone: "(512)887-2937",
    streetAddress: "812 Airport Blvd.",
    city: "Austin",
    state: "TX",
    zipcode: 78702,
    website: "https://www.urbanaxes.com/austin",
    maxOccupancy: 125,
    allowedOccupancyRestriction: 25,
    profileImage: "",
    active: false,
  },
  {
    businessId: 5,
    businessName: "Women and Their Work",
    businessPhone: "(512)477-1064",
    streetAddress: "1710 Lavaca St.",
    city: "Austin",
    state: "TX",
    zipcode: 78701,
    website: "http://womenandtheirwork.org",
    maxOccupancy: 250,
    allowedOccupancyRestriction: 0,
    profileImage: "",
    active: false,
  },
];
